"""
Fixed board topology constants for the standard Catan map.

Extracted from Catanatron's CatanMap. These are invariant across games --
only tile resources/numbers and port resource assignments change per game.

Tile IDs 0-18 correspond to the 19 land tiles in BFS order from center.
Node IDs 0-53 correspond to the 54 settlement positions.

Generated by extract_board_constants.py
"""

# Tile ID -> cube coordinate (x, y, z) where x + y + z = 0
# Layer 0 (center): tile 0
# Layer 1 (ring 1): tiles 1-6
# Layer 2 (ring 2): tiles 7-18
TILE_ID_TO_COORD = {
    0: (0, 0, 0),
    1: (1, -1, 0),
    2: (0, -1, 1),
    3: (-1, 0, 1),
    4: (-1, 1, 0),
    5: (0, 1, -1),
    6: (1, 0, -1),
    7: (2, -2, 0),
    8: (1, -2, 1),
    9: (0, -2, 2),
    10: (-1, -1, 2),
    11: (-2, 0, 2),
    12: (-2, 1, 1),
    13: (-2, 2, 0),
    14: (-1, 2, -1),
    15: (0, 2, -2),
    16: (1, 1, -2),
    17: (2, 0, -2),
    18: (2, -1, -1),
}

COORD_TO_TILE_ID = {v: k for k, v in TILE_ID_TO_COORD.items()}

# Node ID -> list of adjacent land tile IDs
# Interior nodes touch 3 tiles, edge nodes touch 1-2 tiles
NODE_TO_TILE_IDS = {
    0: [0, 5, 6],
    1: [0, 1, 6],
    2: [0, 1, 2],
    3: [0, 2, 3],
    4: [0, 3, 4],
    5: [0, 4, 5],
    6: [1, 6, 18],
    7: [1, 7, 18],
    8: [1, 7, 8],
    9: [1, 2, 8],
    10: [2, 8, 9],
    11: [2, 9, 10],
    12: [2, 3, 10],
    13: [3, 10, 11],
    14: [3, 11, 12],
    15: [3, 4, 12],
    16: [4, 5, 14],
    17: [4, 12, 13],
    18: [4, 13, 14],
    19: [5, 15, 16],
    20: [5, 6, 16],
    21: [5, 14, 15],
    22: [6, 16, 17],
    23: [6, 17, 18],
    24: [7, 18],
    25: [7],
    26: [7],
    27: [7, 8],
    28: [8],
    29: [8, 9],
    30: [9],
    31: [9],
    32: [9, 10],
    33: [10],
    34: [10, 11],
    35: [11],
    36: [11],
    37: [11, 12],
    38: [12],
    39: [12, 13],
    40: [13, 14],
    41: [13],
    42: [13],
    43: [14, 15],
    44: [14],
    45: [15],
    46: [15, 16],
    47: [15],
    48: [16],
    49: [16, 17],
    50: [17],
    51: [17],
    52: [17, 18],
    53: [18],
}

# Node ID -> list of adjacent node IDs (connected by road edges)
NODE_ADJACENCY = {
    0: [1, 5, 20],
    1: [0, 2, 6],
    2: [1, 3, 9],
    3: [2, 4, 12],
    4: [3, 5, 15],
    5: [0, 4, 16],
    6: [1, 7, 23],
    7: [6, 8, 24],
    8: [7, 9, 27],
    9: [2, 8, 10],
    10: [9, 11, 29],
    11: [10, 12, 32],
    12: [3, 11, 13],
    13: [12, 14, 34],
    14: [13, 15, 37],
    15: [4, 14, 17],
    16: [5, 18, 21],
    17: [15, 18, 39],
    18: [16, 17, 40],
    19: [20, 21, 46],
    20: [0, 19, 22],
    21: [16, 19, 43],
    22: [20, 23, 49],
    23: [6, 22, 52],
    24: [7, 25, 53],
    25: [24, 26],
    26: [25, 27],
    27: [8, 26, 28],
    28: [27, 29],
    29: [10, 28, 30],
    30: [29, 31],
    31: [30, 32],
    32: [11, 31, 33],
    33: [32, 34],
    34: [13, 33, 35],
    35: [34, 36],
    36: [35, 37],
    37: [14, 36, 38],
    38: [37, 39],
    39: [17, 38, 41],
    40: [18, 42, 44],
    41: [39, 42],
    42: [40, 41],
    43: [21, 44, 47],
    44: [40, 43],
    45: [46, 47],
    46: [19, 45, 48],
    47: [43, 45],
    48: [46, 49],
    49: [22, 48, 50],
    50: [49, 51],
    51: [50, 52],
    52: [23, 51, 53],
    53: [24, 52],
}

# Port coordinate -> pair of land node IDs that get port access
# The resource assigned to each port varies per game (read from board_layout).
# Ports with resource=null in the data are 3:1 generic ports.
PORT_COORD_TO_NODES = {
    (-3, 0, 3): [35, 36],
    (-3, 2, 1): [38, 39],
    (-2, 3, -1): [40, 44],
    (-1, -2, 3): [32, 33],
    (0, 3, -3): [45, 47],
    (1, -3, 2): [28, 29],
    (2, 1, -3): [48, 49],
    (3, -3, 0): [25, 26],
    (3, -1, -2): [52, 53],
}

# Dice number -> probability (out of 36 total outcomes)
# Used to compute production value for each tile
NUMBER_PROBABILITIES = {
    2: 1 / 36,
    3: 2 / 36,
    4: 3 / 36,
    5: 4 / 36,
    6: 5 / 36,
    7: 6 / 36,
    8: 5 / 36,
    9: 4 / 36,
    10: 3 / 36,
    11: 2 / 36,
    12: 1 / 36,
}

RESOURCES = ["BRICK", "WOOD", "SHEEP", "WHEAT", "ORE"]

NUM_NODES = 54
NUM_TILES = 19
